apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-cache
  name: http-cache
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: http-cache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: http-cache
        group: streaming
    spec:
      containers:
      - image: bitnami/openresty:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 250m
            ephemeral-storage: 10Mi
            memory: 256Mi
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - mountPath: /opt/bitnami/openresty/nginx/conf/server_blocks/default.conf
          name: http-cache-config
          subPath: nginx.conf
        - mountPath: /opt/bitnami/openresty/nginx/conf/server_blocks/default.conf
          name: http-cache-config
          subPath: nginx.conf
        - mountPath: /cache/static
          name: static-cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: static-cache
        emptyDir: {}
      - configMap:
          defaultMode: 420
          name: http-cache-config
        name: http-cache-config
